name: Docker Image CI

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build and Push Docker Image
      id: build
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: astranger/all-the-mods-6-sky
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        tags: latest
    - name: Add latest tag
      uses: tinact/docker.image-retag@1.0.2
      with:
        image_name: astranger/all-the-mods-6-sky
        image_old_tag: ${{ steps.build.outputs.tags }}
        image_new_tag: latest
        registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
        registry_password: ${{ secrets.DOCKERHUB_TOKEN }}